<a href="https://colab.research.google.com/github/surendra3474/takeobds41/blob/main/1_9_2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Preprosessing

Import Library

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Import Data

In [2]:
url = '/content/camera.csv'
df = pd.read_csv(url)
df

Colour  Length    Pixel Purchased
0     Red    44.0  72000.0        No
1  Yellow    27.0  48000.0       Yes
2    Blue    30.0  54000.0        No
3  Yellow    38.0  61000.0        No
4    Blue    40.0      NaN       Yes
5     Red    35.0  58000.0       Yes
6  Yellow     NaN  52000.0        No
7     Red    48.0  79000.0       Yes
8    Blue    50.0  83000.0        No
9     Red    37.0  67000.0       Yes

Independent and Dependent Values

In [3]:
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [5]:
X

array([['Red', 44.0, 72000.0],
       ['Yellow', 27.0, 48000.0],
       ['Blue', 30.0, 54000.0],
       ['Yellow', 38.0, 61000.0],
       ['Blue', 40.0, nan],
       ['Red', 35.0, 58000.0],
       ['Yellow', nan, 52000.0],
       ['Red', 48.0, 79000.0],
       ['Blue', 50.0, 83000.0],
       ['Red', 37.0, 67000.0]], dtype=object)

In [6]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

Replacing the Missing Data

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [8]:
X

array([['Red', 44.0, 72000.0],
       ['Yellow', 27.0, 48000.0],
       ['Blue', 30.0, 54000.0],
       ['Yellow', 38.0, 61000.0],
       ['Blue', 40.0, 63777.77777777778],
       ['Red', 35.0, 58000.0],
       ['Yellow', 38.77777777777778, 52000.0],
       ['Red', 48.0, 79000.0],
       ['Blue', 50.0, 83000.0],
       ['Red', 37.0, 67000.0]], dtype=object)

Encoding Categorical Data

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
X

array([[1.0, 0.0, 1.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 1.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 1.0, 0.0, 37.0, 67000.0]], dtype=object)

Label encoding

In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

Splitting the dataset to the Training set and Test Set

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 1/5, random_state=0)

In [15]:
X_train, X_test, y_train, y_test

(array([[0.0, 1.0, 0.0, 0.0, 40.0, 63777.77777777778],
        [1.0, 0.0, 1.0, 0.0, 37.0, 67000.0],
        [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
        [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
        [1.0, 0.0, 1.0, 0.0, 48.0, 79000.0],
        [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
        [1.0, 0.0, 1.0, 0.0, 44.0, 72000.0],
        [1.0, 0.0, 1.0, 0.0, 35.0, 58000.0]], dtype=object),
 array([[0.0, 1.0, 0.0, 0.0, 30.0, 54000.0],
        [0.0, 1.0, 0.0, 0.0, 50.0, 83000.0]], dtype=object),
 array([1, 1, 1, 0, 1, 0, 0, 1]),
 array([0, 0]))

Feature Selection

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])

In [16]:
X_train

array([[0.0, 1.0, 0.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 1.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 1.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 1.0, 0.0, 35.0, 58000.0]], dtype=object)